//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from e:\ZhiDaoLang\ZDLang\ZDLang_Antlr\ZD.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class ZDLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, KEY=27, IDENTIFIER=28, WS=29, NUMBER=30;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "T__11", "T__12", "T__13", "T__14", "T__15", "T__16", 
		"T__17", "T__18", "T__19", "T__20", "T__21", "T__22", "T__23", "T__24", 
		"T__25", "KEY", "IDENTIFIER", "WS", "NUMBER", "DIGIT", "CHINESE"
	};


	public ZDLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public ZDLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'\u00B7\u5F15'", "'\u300A'", "'-'", "'\u300B'", "'\u00B7\u4E66'", 
		"'\u00B7\u7AE0'", "'\u00B7\u8005'", "'\u00B7\u4E5F'", "'\uFF1B'", "'\u00B7\u4EE5'", 
		"'\uFF08'", "'\uFF0C'", "'\uFF09'", "'\u00B7\u8BBE'", "'\u00B7\u4E3A'", 
		"'\u2018'", "'\u9225\uFFFD'", "'\u2019'", "'\u201C'", "'\u201D'", "'\u00B7\u94B8'", 
		"'\u00B7\u533F'", "'\u00B7\u4F20'", "'\u00B7\u66F0'", "'\u3002'", "'\u00B7\u4ECB'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, "KEY", "IDENTIFIER", "WS", "NUMBER"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "ZD.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static ZDLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', ' ', '\xBF', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\r', 
		'\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', 
		'\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', 
		'\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', 
		'\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x3', 
		'\x19', '\x3', '\x19', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x3', 
		'\x1B', '\x3', '\x1B', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', 
		'\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', 
		'\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', 
		'\x1C', '\x5', '\x1C', '\x94', '\n', '\x1C', '\x3', '\x1D', '\x6', '\x1D', 
		'\x97', '\n', '\x1D', '\r', '\x1D', '\xE', '\x1D', '\x98', '\x3', '\x1D', 
		'\x3', '\x1D', '\a', '\x1D', '\x9D', '\n', '\x1D', '\f', '\x1D', '\xE', 
		'\x1D', '\xA0', '\v', '\x1D', '\x3', '\x1E', '\x6', '\x1E', '\xA3', '\n', 
		'\x1E', '\r', '\x1E', '\xE', '\x1E', '\xA4', '\x3', '\x1E', '\x3', '\x1E', 
		'\x3', '\x1F', '\x5', '\x1F', '\xAA', '\n', '\x1F', '\x3', '\x1F', '\x3', 
		'\x1F', '\x3', '\x1F', '\x5', '\x1F', '\xAF', '\n', '\x1F', '\x3', '\x1F', 
		'\x3', '\x1F', '\x5', '\x1F', '\xB3', '\n', '\x1F', '\x3', '\x1F', '\x5', 
		'\x1F', '\xB6', '\n', '\x1F', '\x3', ' ', '\x6', ' ', '\xB9', '\n', ' ', 
		'\r', ' ', '\xE', ' ', '\xBA', '\x3', '!', '\x5', '!', '\xBE', '\n', '!', 
		'\x2', '\x2', '\"', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', 
		'\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', 
		'\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', 
		'\x11', '!', '\x12', '#', '\x13', '%', '\x14', '\'', '\x15', ')', '\x16', 
		'+', '\x17', '-', '\x18', '/', '\x19', '\x31', '\x1A', '\x33', '\x1B', 
		'\x35', '\x1C', '\x37', '\x1D', '\x39', '\x1E', ';', '\x1F', '=', ' ', 
		'?', '\x2', '\x41', '\x2', '\x3', '\x2', '\a', '\x3', '\x2', '\x32', ';', 
		'\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', '\x4', '\x2', '-', 
		'-', '/', '/', '\x4', '\x2', 'G', 'G', 'g', 'g', '\x4', '\x2', '\x63', 
		'|', '\x4E02', '\xA001', '\x2', '\xCB', '\x2', '\x3', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', 
		'\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x33', '\x3', '\x2', '\x2', '\x2', '\x2', '\x35', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x37', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x39', '\x3', '\x2', '\x2', '\x2', '\x2', ';', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '=', '\x3', '\x2', '\x2', '\x2', '\x3', '\x43', '\x3', '\x2', '\x2', 
		'\x2', '\x5', '\x46', '\x3', '\x2', '\x2', '\x2', '\a', 'H', '\x3', '\x2', 
		'\x2', '\x2', '\t', 'J', '\x3', '\x2', '\x2', '\x2', '\v', 'L', '\x3', 
		'\x2', '\x2', '\x2', '\r', 'O', '\x3', '\x2', '\x2', '\x2', '\xF', 'R', 
		'\x3', '\x2', '\x2', '\x2', '\x11', 'U', '\x3', '\x2', '\x2', '\x2', '\x13', 
		'X', '\x3', '\x2', '\x2', '\x2', '\x15', 'Z', '\x3', '\x2', '\x2', '\x2', 
		'\x17', ']', '\x3', '\x2', '\x2', '\x2', '\x19', '_', '\x3', '\x2', '\x2', 
		'\x2', '\x1B', '\x61', '\x3', '\x2', '\x2', '\x2', '\x1D', '\x63', '\x3', 
		'\x2', '\x2', '\x2', '\x1F', '\x66', '\x3', '\x2', '\x2', '\x2', '!', 
		'i', '\x3', '\x2', '\x2', '\x2', '#', 'k', '\x3', '\x2', '\x2', '\x2', 
		'%', 'n', '\x3', '\x2', '\x2', '\x2', '\'', 'p', '\x3', '\x2', '\x2', 
		'\x2', ')', 'r', '\x3', '\x2', '\x2', '\x2', '+', 't', '\x3', '\x2', '\x2', 
		'\x2', '-', 'w', '\x3', '\x2', '\x2', '\x2', '/', 'z', '\x3', '\x2', '\x2', 
		'\x2', '\x31', '}', '\x3', '\x2', '\x2', '\x2', '\x33', '\x80', '\x3', 
		'\x2', '\x2', '\x2', '\x35', '\x82', '\x3', '\x2', '\x2', '\x2', '\x37', 
		'\x93', '\x3', '\x2', '\x2', '\x2', '\x39', '\x96', '\x3', '\x2', '\x2', 
		'\x2', ';', '\xA2', '\x3', '\x2', '\x2', '\x2', '=', '\xA9', '\x3', '\x2', 
		'\x2', '\x2', '?', '\xB8', '\x3', '\x2', '\x2', '\x2', '\x41', '\xBD', 
		'\x3', '\x2', '\x2', '\x2', '\x43', '\x44', '\a', '\xB9', '\x2', '\x2', 
		'\x44', '\x45', '\a', '\x5F17', '\x2', '\x2', '\x45', '\x4', '\x3', '\x2', 
		'\x2', '\x2', '\x46', 'G', '\a', '\x300C', '\x2', '\x2', 'G', '\x6', '\x3', 
		'\x2', '\x2', '\x2', 'H', 'I', '\a', '/', '\x2', '\x2', 'I', '\b', '\x3', 
		'\x2', '\x2', '\x2', 'J', 'K', '\a', '\x300D', '\x2', '\x2', 'K', '\n', 
		'\x3', '\x2', '\x2', '\x2', 'L', 'M', '\a', '\xB9', '\x2', '\x2', 'M', 
		'N', '\a', '\x4E68', '\x2', '\x2', 'N', '\f', '\x3', '\x2', '\x2', '\x2', 
		'O', 'P', '\a', '\xB9', '\x2', '\x2', 'P', 'Q', '\a', '\x7AE2', '\x2', 
		'\x2', 'Q', '\xE', '\x3', '\x2', '\x2', '\x2', 'R', 'S', '\a', '\xB9', 
		'\x2', '\x2', 'S', 'T', '\a', '\x8007', '\x2', '\x2', 'T', '\x10', '\x3', 
		'\x2', '\x2', '\x2', 'U', 'V', '\a', '\xB9', '\x2', '\x2', 'V', 'W', '\a', 
		'\x4E61', '\x2', '\x2', 'W', '\x12', '\x3', '\x2', '\x2', '\x2', 'X', 
		'Y', '\a', '\xFF1D', '\x2', '\x2', 'Y', '\x14', '\x3', '\x2', '\x2', '\x2', 
		'Z', '[', '\a', '\xB9', '\x2', '\x2', '[', '\\', '\a', '\x4EE7', '\x2', 
		'\x2', '\\', '\x16', '\x3', '\x2', '\x2', '\x2', ']', '^', '\a', '\xFF0A', 
		'\x2', '\x2', '^', '\x18', '\x3', '\x2', '\x2', '\x2', '_', '`', '\a', 
		'\xFF0E', '\x2', '\x2', '`', '\x1A', '\x3', '\x2', '\x2', '\x2', '\x61', 
		'\x62', '\a', '\xFF0B', '\x2', '\x2', '\x62', '\x1C', '\x3', '\x2', '\x2', 
		'\x2', '\x63', '\x64', '\a', '\xB9', '\x2', '\x2', '\x64', '\x65', '\a', 
		'\x8BC0', '\x2', '\x2', '\x65', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x66', 
		'g', '\a', '\xB9', '\x2', '\x2', 'g', 'h', '\a', '\x4E3C', '\x2', '\x2', 
		'h', ' ', '\x3', '\x2', '\x2', '\x2', 'i', 'j', '\a', '\x201A', '\x2', 
		'\x2', 'j', '\"', '\x3', '\x2', '\x2', '\x2', 'k', 'l', '\a', '\x9227', 
		'\x2', '\x2', 'l', 'm', '\a', '\xFFFF', '\x2', '\x2', 'm', '$', '\x3', 
		'\x2', '\x2', '\x2', 'n', 'o', '\a', '\x201B', '\x2', '\x2', 'o', '&', 
		'\x3', '\x2', '\x2', '\x2', 'p', 'q', '\a', '\x201E', '\x2', '\x2', 'q', 
		'(', '\x3', '\x2', '\x2', '\x2', 'r', 's', '\a', '\x201F', '\x2', '\x2', 
		's', '*', '\x3', '\x2', '\x2', '\x2', 't', 'u', '\a', '\xB9', '\x2', '\x2', 
		'u', 'v', '\a', '\x94BA', '\x2', '\x2', 'v', ',', '\x3', '\x2', '\x2', 
		'\x2', 'w', 'x', '\a', '\xB9', '\x2', '\x2', 'x', 'y', '\a', '\x5341', 
		'\x2', '\x2', 'y', '.', '\x3', '\x2', '\x2', '\x2', 'z', '{', '\a', '\xB9', 
		'\x2', '\x2', '{', '|', '\a', '\x4F22', '\x2', '\x2', '|', '\x30', '\x3', 
		'\x2', '\x2', '\x2', '}', '~', '\a', '\xB9', '\x2', '\x2', '~', '\x7F', 
		'\a', '\x66F2', '\x2', '\x2', '\x7F', '\x32', '\x3', '\x2', '\x2', '\x2', 
		'\x80', '\x81', '\a', '\x3004', '\x2', '\x2', '\x81', '\x34', '\x3', '\x2', 
		'\x2', '\x2', '\x82', '\x83', '\a', '\xB9', '\x2', '\x2', '\x83', '\x84', 
		'\a', '\x4ECD', '\x2', '\x2', '\x84', '\x36', '\x3', '\x2', '\x2', '\x2', 
		'\x85', '\x86', '\a', '\xB9', '\x2', '\x2', '\x86', '\x94', '\a', '\x5F17', 
		'\x2', '\x2', '\x87', '\x88', '\a', '\xB9', '\x2', '\x2', '\x88', '\x94', 
		'\a', '\x4E68', '\x2', '\x2', '\x89', '\x8A', '\a', '\xB9', '\x2', '\x2', 
		'\x8A', '\x94', '\a', '\x7AE2', '\x2', '\x2', '\x8B', '\x8C', '\a', '\xB9', 
		'\x2', '\x2', '\x8C', '\x94', '\a', '\x8BC0', '\x2', '\x2', '\x8D', '\x8E', 
		'\a', '\xB9', '\x2', '\x2', '\x8E', '\x94', '\a', '\x4E3C', '\x2', '\x2', 
		'\x8F', '\x90', '\a', '\xB9', '\x2', '\x2', '\x90', '\x94', '\a', '\x5B59', 
		'\x2', '\x2', '\x91', '\x92', '\a', '\xB9', '\x2', '\x2', '\x92', '\x94', 
		'\a', '\x53E7', '\x2', '\x2', '\x93', '\x85', '\x3', '\x2', '\x2', '\x2', 
		'\x93', '\x87', '\x3', '\x2', '\x2', '\x2', '\x93', '\x89', '\x3', '\x2', 
		'\x2', '\x2', '\x93', '\x8B', '\x3', '\x2', '\x2', '\x2', '\x93', '\x8D', 
		'\x3', '\x2', '\x2', '\x2', '\x93', '\x8F', '\x3', '\x2', '\x2', '\x2', 
		'\x93', '\x91', '\x3', '\x2', '\x2', '\x2', '\x94', '\x38', '\x3', '\x2', 
		'\x2', '\x2', '\x95', '\x97', '\x5', '\x41', '!', '\x2', '\x96', '\x95', 
		'\x3', '\x2', '\x2', '\x2', '\x97', '\x98', '\x3', '\x2', '\x2', '\x2', 
		'\x98', '\x96', '\x3', '\x2', '\x2', '\x2', '\x98', '\x99', '\x3', '\x2', 
		'\x2', '\x2', '\x99', '\x9E', '\x3', '\x2', '\x2', '\x2', '\x9A', '\x9D', 
		'\x5', '\x41', '!', '\x2', '\x9B', '\x9D', '\t', '\x2', '\x2', '\x2', 
		'\x9C', '\x9A', '\x3', '\x2', '\x2', '\x2', '\x9C', '\x9B', '\x3', '\x2', 
		'\x2', '\x2', '\x9D', '\xA0', '\x3', '\x2', '\x2', '\x2', '\x9E', '\x9C', 
		'\x3', '\x2', '\x2', '\x2', '\x9E', '\x9F', '\x3', '\x2', '\x2', '\x2', 
		'\x9F', ':', '\x3', '\x2', '\x2', '\x2', '\xA0', '\x9E', '\x3', '\x2', 
		'\x2', '\x2', '\xA1', '\xA3', '\t', '\x3', '\x2', '\x2', '\xA2', '\xA1', 
		'\x3', '\x2', '\x2', '\x2', '\xA3', '\xA4', '\x3', '\x2', '\x2', '\x2', 
		'\xA4', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA5', '\x3', '\x2', 
		'\x2', '\x2', '\xA5', '\xA6', '\x3', '\x2', '\x2', '\x2', '\xA6', '\xA7', 
		'\b', '\x1E', '\x2', '\x2', '\xA7', '<', '\x3', '\x2', '\x2', '\x2', '\xA8', 
		'\xAA', '\t', '\x4', '\x2', '\x2', '\xA9', '\xA8', '\x3', '\x2', '\x2', 
		'\x2', '\xA9', '\xAA', '\x3', '\x2', '\x2', '\x2', '\xAA', '\xAB', '\x3', 
		'\x2', '\x2', '\x2', '\xAB', '\xAE', '\x5', '?', ' ', '\x2', '\xAC', '\xAD', 
		'\a', '\x30', '\x2', '\x2', '\xAD', '\xAF', '\x5', '?', ' ', '\x2', '\xAE', 
		'\xAC', '\x3', '\x2', '\x2', '\x2', '\xAE', '\xAF', '\x3', '\x2', '\x2', 
		'\x2', '\xAF', '\xB5', '\x3', '\x2', '\x2', '\x2', '\xB0', '\xB2', '\t', 
		'\x5', '\x2', '\x2', '\xB1', '\xB3', '\t', '\x4', '\x2', '\x2', '\xB2', 
		'\xB1', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xB3', '\x3', '\x2', '\x2', 
		'\x2', '\xB3', '\xB4', '\x3', '\x2', '\x2', '\x2', '\xB4', '\xB6', '\x5', 
		'?', ' ', '\x2', '\xB5', '\xB0', '\x3', '\x2', '\x2', '\x2', '\xB5', '\xB6', 
		'\x3', '\x2', '\x2', '\x2', '\xB6', '>', '\x3', '\x2', '\x2', '\x2', '\xB7', 
		'\xB9', '\x4', '\x32', ';', '\x2', '\xB8', '\xB7', '\x3', '\x2', '\x2', 
		'\x2', '\xB9', '\xBA', '\x3', '\x2', '\x2', '\x2', '\xBA', '\xB8', '\x3', 
		'\x2', '\x2', '\x2', '\xBA', '\xBB', '\x3', '\x2', '\x2', '\x2', '\xBB', 
		'@', '\x3', '\x2', '\x2', '\x2', '\xBC', '\xBE', '\t', '\x6', '\x2', '\x2', 
		'\xBD', '\xBC', '\x3', '\x2', '\x2', '\x2', '\xBE', '\x42', '\x3', '\x2', 
		'\x2', '\x2', '\xE', '\x2', '\x93', '\x98', '\x9C', '\x9E', '\xA4', '\xA9', 
		'\xAE', '\xB2', '\xB5', '\xBA', '\xBD', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
