//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from e:\ZhiDaoLang\ZDLang\ZDLang_Antlr\ZD.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ZDParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IZDVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ZDParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] ZDParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ZDParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] ZDParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ZDParser.importer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImporter([NotNull] ZDParser.ImporterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ZDParser.namespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespace([NotNull] ZDParser.NamespaceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ZDParser.class"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass([NotNull] ZDParser.ClassContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ZDParser.property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProperty([NotNull] ZDParser.PropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ZDParser.valueSentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValueSentence([NotNull] ZDParser.ValueSentenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ZDParser.func_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_call([NotNull] ZDParser.Func_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ZDParser.sentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentence([NotNull] ZDParser.SentenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ZDParser.set_val"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSet_val([NotNull] ZDParser.Set_valContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ZDParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar([NotNull] ZDParser.VarContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ZDParser.char"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChar([NotNull] ZDParser.CharContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ZDParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStr([NotNull] ZDParser.StrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ZDParser.new"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNew([NotNull] ZDParser.NewContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ZDParser.access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccess([NotNull] ZDParser.AccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ZDParser.func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc([NotNull] ZDParser.FuncContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ZDParser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParams([NotNull] ZDParser.ParamsContext context);
}
